version: '3.3'
services:
  php-fpm:
    container_name: php-fpm
    build: ./docker/php-fpm
    volumes:
      - ./src:/var/php-fpm

  nginx:
    container_name: nginx
    build: ./docker/nginx
    links:
      - php-fpm
    ports:
      - 80:80